version: '3.8'

services:
  api:
    image: baram987/api-gateway
    ports:
      - "7777:7777"
    links:
      - device

  device:
    image: baram987/device-ms
    container_name: device
    ports:
      - "8000:8000"

  user:
    image: baram987/auth-ms
    container_name: auth
    ports:
      - "9000:9000"

  mosquitto:
    build:
      context: apps/mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"


