export enum API_GATEWAY_ENV {
  PREFIX = 'API_GATEWAY_URL_PREFIX',
  HOST = 'API_GATEWAY_HOST',
  PORT = 'API_GATEWAY_PORT',
  URL = 'API_GATEWAY_URL',
}

export enum DEVICE_MS_ENV {
  PREFIX = 'DEVICE_MS_URL_PREFIX',
  HOST = 'DEVICE_MS_HOST',
  PORT = 'DEVICE_MS_PORT',
  URL = 'DEVICE_MS_URL',
}

export enum USER_MS_ENV {
  PREFIX = 'USER_MS_URL_PREFIX',
  HOST = 'USER_MS_HOST',
  PORT = 'USER_MS_PORT',
  URL = 'USER_MS_URL',
}

export enum JWT_ENV {
  JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
}

export enum COOKIE_ENV {
  COOKIE_DOMAIN = 'COOKIE_DOMAIN',
}

export enum DATABASE_ENV {
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_PORT = 'DATABASE_PORT',
}

export enum REDIS_ENV {
  REDIS_URL = 'REDIS_URL',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
}

export enum MQTT_ENV {
  URL = 'MQTT_BROKER_URL',
}
