name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build
        uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build
          affected: 'true'

